### ISSUE TITLE
No module named 'skrvm'

### ISSUE THREAD

**Issue by BBBBbevrly** [JamesRitchie/scikit-rvm#18]
Hi there,

Thanks so much for the RVM code. However, I met a difficulty at the very beginning. I installed scikit-svm and it said：
![image](https://user-images.githubusercontent.com/51921626/59618968-50611a00-9121-11e9-9541-2ad6ab859b50.png)

I tried to employ it in python though anaconda then but failed:
![image](https://user-images.githubusercontent.com/51921626/59619090-98803c80-9121-11e9-82e2-dc8751b43d50.png)

I don't understand why. Any help will be appreciated. 

Thanks

**Comment by BBBBbevrly** [comment]
Sorry I was just being stupid...

**Comment by oveedh** [comment]
How were you able to resolve this issue? I'm struggling with the same problem.
