### ISSUE TITLE
error with unequal sample sizes for classes

### ISSUE THREAD

**Issue by summeryingliu** [JamesRitchie/scikit-rvm#5]
It seems the RVC function only works when number of both classes are of the same sample size.
When train with a sample with 72 [0] and 78 [1], I receive the following error:
Error in python.exec("clf.fit(H,label)") : 
  operands could not be broadcast together with shapes (72,) (78,) 

It worked when I set both classes with equal size 75 for each.

**Comment by JamesRitchie** [comment]
Fixed by #8.
